version: '3.1'
services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "10000:10000"
      - "9000:9000"
    environment:
      - DEFAULT_REGION=eu-west-1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=9000
      - LAMBDA_EXECUTOR=local
      - DOCKER_HOST=unix:///var/run/docker.sock
      - START_WEB=1

  dynamodb:
    image: amazon/dynamodb-local:latest
    ports:
      - "11000:8000"
    environment:
      AWS_ACCESS_KEY_ID: "123"
      AWS_SECRET_ACCESS_KEY: "123"
      AWS_REGION: ap-northeast-2
    command: [ "-D\"java.library.path\"=./DynamoDBLocal_lib", "-jar", "DynamoDBLocal.jar", "-inMemory", "-sharedDb" ]
